local bufop = require("terminal.bufop")
local common = require("tests.terminal.common")

describe("get content", function()
    it("empty", function()
        local buf = vim.api.nvim_create_buf(true, false)
        local content = bufop.get_buf_content(buf)
        assert.equals("", content)
    end)

    it("ansi file", function()
        local buf = vim.api.nvim_create_buf(true, false)
        vim.api.nvim_buf_set_name(buf, common.ansi_file)
        vim.api.nvim_buf_call(buf, vim.cmd.edit)
        common.sleep(1000)
        local content = bufop.get_buf_content(buf)
        assert.equals(common.ansi_file_content, content)
    end)
end)
